apiVersion: "resource.k8s.io/v1"
kind: "ResourceClaimTemplate"
metadata:
  name: "hf-embed-mig-f8a8c39baa"
  namespace: "hardfest-demo"
  labels:
    app.kubernetes.io/part-of: "hardfest-gpu-workshop"
    app.kubernetes.io/name: "hf-embed-mig"
spec:
  spec:
    devices:
      requests:
        -
          name: "gpu"
          exactly:
            deviceClassName: "REPLACE_GENERATED_MIG_DEVICECLASS"
            allocationMode: "ExactCount"
            count: 1
