apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rtx-models
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.example.com/team/k8s-config.git
    targetRevision: hardfest-rtx
    path: argo-projects/gpu-cluster/hardfest-rtx/charts/model-catalog
    helm:
      releaseName: rtx-models
      valueFiles:
        - ../../catalog/rtx.yaml
  destination:
    name: gpu-cluster
    namespace: hardfest-rtx
  syncPolicy:
    syncOptions: [CreateNamespace=false, ServerSideApply=true]
