apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hardfest-embed-mps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.example.com/team/k8s-config.git
    targetRevision: hardfest-demo
    path: argo-projects/gpu-cluster/hardfest-demo/charts/vllm-runtime
    helm:
      releaseName: hf-embed-mps
      valueFiles:
        - ../../values/embed-mps.yaml
        - ../../site/embed-mps.yaml
  destination:
    name: cluster-with-a30
    namespace: hardfest-demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - PruneLast=true
