apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "hardfest-demo"
resources:
  - "resources.yaml"
configMapGenerator:
  -
    name: "hf-qwen-tp2"
    files:
      - "profile.yaml"
