apiVersion: "v1"
kind: "Service"
metadata:
  name: "hf-qwen-tp2"
  namespace: "hardfest-demo"
  labels:
    app.kubernetes.io/part-of: "hardfest-gpu-workshop"
    app.kubernetes.io/name: "hf-qwen-tp2"
spec:
  selector:
    app.kubernetes.io/name: "hf-qwen-tp2"
  ports:
    -
      name: "http"
      port: 8000
      targetPort: 8000
  type: "ClusterIP"
