apiVersion: "resource.k8s.io/v1"
kind: "ResourceClaimTemplate"
metadata:
  name: "hf-gemma-a-46a09bd858"
  namespace: "hardfest-demo"
  labels:
    app.kubernetes.io/part-of: "hardfest-gpu-workshop"
    app.kubernetes.io/name: "hf-gemma-a"
spec:
  spec:
    devices:
      requests:
        -
          name: "gpu"
          exactly:
            deviceClassName: "REPLACE_GENERATED_H100_DEVICECLASS"
            allocationMode: "ExactCount"
            count: 1
